### PR TITLE
Change nav buttons to anchors

### PR DESCRIPTION
**Pull request by amogusussy**
With forms, you can't use the middle mouse click to open in a new tab, but you can with anchors (\<a\> in html).

This PR changes the buttons to anchors, so you can open in a new tab.

### CODE REVIEW

**Comment by Extravi** [comment]
buttons gone 
image
font does not seem the same also icons are much closer padding seems to be gone and font looks different 
image

before 
image


font has slightly different styling and icons have padding

**Comment by amogusussy** [comment]
I've just fixed it with the most recent two commits.

**Comment by Extravi** [comment]
image

not fixed dont change the style or icons anchors are fine but changing the style is not fine with me even the icons 

it should look like this 
image

**Comment by amogusussy** [comment]
It should be working now (tested on librewolf and ungoogled chromium).

**Comment by amogusussy** [comment]
The sizes seem different on chromium and firefox-based.
I think I've just figured out why. It's because elements on chromium and firefox-based have different sizes.
If you open the 'computed' tab in chromium and use the element selector to select one of the buttons under the search bar, the dimensions are `28.547×17`. But if you do the same in a firefox-based browser, it's `30.5167×17`.
You can see this issue when you open the site in both Chromium and Firefox-based, fullscreen both, then alt tab between them.

So this PR doesn't introduce a new issue, it's just an already present issue.

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
Sorry but I will be doing this separately soon

**Pull request closed without merging**
