### PR TITLE
Send user back to page they were previously on after submitting their settings.

### PR DESCRIPTION
**Pull request by amogusussy**
If you submit the settings form, you get sent to a 404 not found page.

This PR sends the user back to the url they were at before.

### CODE REVIEW

**Comment by Extravi** [comment]
I don't have this issue locally.

I used to have this issue on my server until I removed it from my nginx config, which solved it for me.
```bash
add_header Referrer-Policy "no-referrer" always;
```

https://github.com/Extravi/tailsx-docs/commit/56cfd43fa0945f224c5e8a68e248a9c77a2a7e0b

https://github.com/Extravi/tailsx-docs/blob/main/config/tailsx

**Comment by Extravi** [comment]
you can test it on my instance https://tailsx.extravi.dev/search?q=hello+world&t=text

**Comment by Extravi** [comment]
works in both results and settings

**Comment by amogusussy** [comment]
It doesn't work for me on your instance.

Your instance: https://0x0.st/HQVO.mkv
Localhost with this PR: https://0x0.st/HQVV.mkv

**Comment by Extravi** [comment]
i dont have this issue on both firefox and chromium try a different browser or something

https://github.com/Extravi/tailsx/assets/98912029/224b53c3-e4fc-46a2-8bb3-894d86248901

**Comment by amogusussy** [comment]
For some reason, it doesn't work in librewolf, but does in ungoogled chromium.
It might still be good to merge for the cases when it doesn't work.

**Comment by Extravi** [comment]
alright let me test it first

**Comment by Extravi** [comment]
i will find a better solution for the css soon i don't like having blank space

**Comment by Extravi** [comment]
alright everything works thank you :)

**Pull request merged**
